<?php

namespace AppBundle\Repository\JRFMarine\Categoria;

/**
 * SubcategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
