<?php

namespace AppBundle\Repository\Astillero\Proveedor;

/**
 * BancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BancoRepository extends \Doctrine\ORM\EntityRepository
{
}
