<?php

namespace AppBundle\Repository\Astillero\Proveedor;

/**
 * CatalogoTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogoTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
