<?php

namespace AppBundle\Repository\Tienda;

/**
 * PeticionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeticionRepository extends \Doctrine\ORM\EntityRepository
{
}
