<?php

namespace AppBundle\Repository\Tienda;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
    public function borrarProducto($producto)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->delete('AppBundle:Tienda\Producto', 'prod')
            ->where('prod.id = :producto')
            ->setParameter('producto', $producto)
            ->getQuery()
            ->execute();
    }
}
