<?php

namespace AppBundle\Repository\Tienda;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends \Doctrine\ORM\EntityRepository
{
    public function validarSolicitud($estado, $validacion, $columna)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->update('AppBundle:Tienda\Solicitud', 's')
            ->set($columna, ':uno')
            ->where('s.id = :var')
            ->setParameter('var', $estado)
            ->setParameter('uno', $validacion)
            ->getQuery()
            ->execute();
    }
}