<?php

namespace AppBundle\Repository\Tienda\Inventario\Registro;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaRepository extends \Doctrine\ORM\EntityRepository
{
}
