<?php

namespace AppBundle\Repository\JRFMarine;

/**
 * MarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaRepository extends \Doctrine\ORM\EntityRepository
{
}
