<?php

namespace AppBundle\Repository\Producto;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function paginacion($page = 1, $length = 10, $order = 'DESC')
    {
        $qb = $this->createQueryBuilder('cat');
        $qb
            ->addOrderBy('cat.id', 'DESC')
            ->setFirstResult($length * ((int)$page - 1))
            ->setMaxResults($length);


        $paginator = new Paginator($qb, false);

        return $paginator;
    }
}
