<?php

namespace AppBundle\Repository\Producto;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * SubcategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaRepository extends EntityRepository
{
    public function paginacion($page = 1, $length = 10, $order = 'DESC', $categoria = null) : Paginator
    {
        $qb = $this->createQueryBuilder('sub');

        $qb
            ->select('sub', 'cat')
            ->leftJoin('sub.categoria', 'cat')
            ->addOrderBy('sub.id', $order)
            ->setFirstResult($length * ((int)$page - 1))
            ->setMaxResults($length);

        if ($categoria) {
            $qb
                ->where($qb->expr()->eq('cat', ':categoria'))
                ->setParameter('categoria', $categoria);
        }

        return new Paginator($qb, true);
    }
}
