<?php

namespace AppBundle\Repository\Astillero;

/**
 * ContratistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratistaRepository extends \Doctrine\ORM\EntityRepository
{
}
