<?php

namespace AppBundle\Repository\Astillero;
use Doctrine\ORM\Internal\Hydration\ArrayHydrator;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
    function obtenerProducto($idproducto)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p.id,p.nombre,p.precio,p.unidad,p.identificador ' .
                'FROM AppBundle:Astillero\Producto p '.
                'WHERE p.id = :id'
            )
            ->setParameter('id',$idproducto);
        return $query->getArrayResult()[0];
    }
}
