<?php

namespace AppBundle\Repository\Astillero;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProveedorNameLike($query)
    {
        return $this->createQueryBuilder('p')
            ->select('p.id AS id', 'p.nombre AS nombre')
            ->where('p.nombre LIKE :query')
            ->setParameter('query', "%{$query}%")
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();
    }
}
