<?php

namespace AppBundle\Repository;

/**
 * AstilleroContratistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstilleroContratistaRepository extends \Doctrine\ORM\EntityRepository
{
}
