<?php

namespace AppBundle\Repository;

/**
 * AstilleroCotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstilleroCotizacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function soloAceptados()
    {
        $qb = $this->createQueryBuilder('ac');

        return $qb
            ->select('ac')
            ->where($qb->expr()->eq('ac.validacliente',2))
            ->getQuery()
            ->getResult();
    }

    public function getCotizacionByFolio($folio)
    {
        $folios = explode('-', $folio);

        $qb = $this->createQueryBuilder('atc');

        $qb->where('atc.folio = :folio')
            ->setParameter('folio', $folios[0]);

        if (isset($folios[1])) {
            $qb->andWhere('atc.foliorecotiza = :foliorecotiza')
                ->setParameter('foliorecotiza', $folios[1]);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
