<?php

namespace AppBundle\Repository;

/**
 * AstilleroCotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstilleroCotizacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function soloAceptados()
    {
        $qb = $this->createQueryBuilder('ac');

        return $qb
            ->select('ac')
            ->where($qb->expr()->eq('ac.validacliente',2))
            ->getQuery()
            ->getResult();
    }
}
