<?php

namespace AppBundle\Repository;

/**
 * AstilleroServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstilleroServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
