<?php

namespace AppBundle\Repository;

/**
 * BarcoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarcoRepository extends \Doctrine\ORM\EntityRepository
{
}
