<?php

namespace AppBundle\Repository;

/**
 * CombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombustibleRepository extends \Doctrine\ORM\EntityRepository
{
}
