<?php

namespace AppBundle\Repository;

/**
 * correoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorreoRepository extends \Doctrine\ORM\EntityRepository
{
    public function OrdenaUnoLista()
    {
        $qb = $this->createQueryBuilder('c');
        return $qb
            ->select('c')
            ->orderBy('c.id','DESC')
            ->getQuery()
            ->getResult();
    }
}
