<?php

namespace AppBundle\Repository;

/**
 * CotizacionNotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotizacionNotaRepository extends \Doctrine\ORM\EntityRepository
{
}
