<?php

namespace AppBundle\Repository;

/**
 * EmbarcacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionRepository extends \Doctrine\ORM\EntityRepository
{
}
