<?php

namespace AppBundle\Repository;

/**
 * EmbarcacionImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionImagenRepository extends \Doctrine\ORM\EntityRepository
{
}
