<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmbarcacionModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionModeloRepository extends \Doctrine\ORM\EntityRepository
{
    public function paginacion($current = 1, $size = 10, $order = 'DESC', $marca = null)
    {
        $qb = $this->createQueryBuilder('modelo');

        $qb
            ->select('modelo.id', 'modelo.nombre', 'marca.id idmarca', 'marca.nombre nombremarca')
            ->leftJoin('modelo.marca', 'marca')
            ->orderBy('modelo.id', 'DESC')
            ->addOrderBy('modelo.nombre', $order)
            ->setFirstResult($size * ((int)$current - 1))
            ->setMaxResults($size);

        if ($marca) {
            $qb
                ->where($qb->expr()->eq('marca.id', ':marca'))
                ->setParameter(':marca', $marca);
        }

        $paginator = new Paginator($qb, false);
        $paginator
            ->setUseOutputWalkers(false);

        $total = $paginator->count();
        $pages = ceil($total / $size);

        return ['modelos' => $paginator, 'total' => $total, 'pages' => $pages];
    }
}
