<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmbarcacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param int $limit
     *
     * @return Paginator
     */
    public function paginacion($page = 1, $limit = 10)
    {
        $qb = $this->createQueryBuilder('em');

        $qb->select('em', 'ma', 'mo', 'pa')
            ->leftJoin('em.marca', 'ma')
            ->leftJoin('em.modelo', 'mo')
            ->leftJoin('em.pais', 'pa')
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return new Paginator($qb, true);

        // Alternativa usando DQL
        /*$em = $this->getEntityManager();
        $dql = 'SELECT em, ma, mo FROM AppBundle:Embarcacion em LEFT JOIN em.marca ma LEFT JOIN em.modelo mo';
        $query = $em->createQuery($dql);

        return $query->getResult();*/
    }
}
