<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmbarcacionMarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionMarcaRepository extends EntityRepository
{
    public function paginacion($current = 1, $size = 10, $order = 'DESC')
    {
        $qb = $this->createQueryBuilder('marca');

        $qb
            ->select('marca.id', 'marca.nombre', 'marca.imagen')
            ->orderBy('marca.id', 'DESC')
            ->addOrderBy('marca.nombre', $order)
            ->setFirstResult($size * ((int)$current - 1))
            ->setMaxResults($size);

        $paginator = new Paginator($qb, false);
        $paginator
            ->setUseOutputWalkers(false);

        $total = $paginator->count();
        $pages = ceil($total / $size);

        return ['marcas' => $paginator, 'total' => $total, 'pages' => $pages];
    }

    public function encuentraMarcas()
    {
        $qb = $this->createQueryBuilder('ma');
        return $qb->select('ma.id','ma.nombre')
            ->getQuery()
            ->getResult();
    }
}
