<?php

namespace AppBundle\Repository;

/**
 * EmbarcacionLayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionLayoutRepository extends \Doctrine\ORM\EntityRepository
{
}
