<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * EmbarcacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbarcacionRepository extends EntityRepository
{
    public function findAllLight()
    {
        $qb = $this->createQueryBuilder('em');

        $qb->select('em', 'ma', 'mo', 'pa')
            ->leftJoin('em.marca', 'ma')
            ->leftJoin('em.modelo', 'mo')
            ->leftJoin('em.pais', 'pa');

        return $qb->getQuery()->getResult();
    }

    public function findAnos()
    {
        $qb = $this->createQueryBuilder('em');

        return $qb->select('em.ano as nombre')
            ->getQuery()
            ->getResult();
    }

    public function findPaises()
    {
        $qb = $this->createQueryBuilder('em');

        return $qb->select('pa.name as nombre')
            ->leftJoin('em.pais', 'pa')
            ->getQuery()
            ->getResult();
    }

    public function findMarcas()
    {
        $qb = $this->createQueryBuilder('em');

        return $qb->select('ma.nombre')
            ->leftJoin('em.marca', 'ma')
            ->getQuery()
            ->getResult();
    }

    public function findModelos()
    {
        $qb = $this->createQueryBuilder('em');

        return $qb->select('mo.nombre')
            ->leftJoin('em.modelo', 'mo')
            ->getQuery()
            ->getResult();
    }
}
