<?php

namespace AppBundle\Repository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends \Doctrine\ORM\EntityRepository
{
    public function eventosVisibles($idusuario)
    {
        $qb = $this->createQueryBuilder('e');
        return $qb->select('e')
            ->where($qb->expr()->eq('e.usuario',':idusuario'))
            ->orWhere($qb->expr()->eq('e.isPublico',true))
            ->setParameter('idusuario',$idusuario)
            ->getQuery()
            ->getResult();
    }
}
