<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaServicioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getServicioCatalogo($servicioId)
    {
        $qry = $this->getEntityManager()
            ->createQuery('SELECT mhs.nombre, mhs.existencia, mhs.unidad, mhs.precio '.
                'FROM AppBundle:MarinaHumedaServicio mhs '.
                'WHERE mhs.id = :id'
            )->setParameter('id', $servicioId);

        return $qry->getArrayResult()[0];
    }

    public function getProductoSelect2($query)
    {
        $builder = $this->createQueryBuilder('producto');

        return $builder
            ->select('producto.id, producto.nombre AS text, producto.existencia AS quantity')
            ->where('LOWER(producto.nombre) LIKE :query')
            ->setParameter('query', strtolower("%{$query}%"))
            ->setMaxResults(5)
            ->getQuery()
            ->getArrayResult();
    }
}
