<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaCotizacionAdicionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaCotizacionAdicionalRepository extends \Doctrine\ORM\EntityRepository
{
}
