<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaSolicitudGasolinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaSolicitudGasolinaRepository extends \Doctrine\ORM\EntityRepository
{
}
