<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaCotizacionAdicionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaCotizacionAdicionalRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllClientes()
    {
        $qb = $this->createQueryBuilder('mca');

        return $qb
            ->select('cliente.nombre AS nombre')
            ->leftJoin('mca.cliente', 'cliente')
            ->distinct()
            ->getQuery()
            ->getResult();
    }
    public function getAllBarcos()
    {
        $qb = $this->createQueryBuilder('mca');

        return $qb
            ->select('barco.nombre AS nombre')
            ->leftJoin('mca.barco', 'barco')
            ->distinct()
            ->getQuery()
            ->getResult();
    }
}
