<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaCotizaServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaCotizaServiciosRepository extends \Doctrine\ORM\EntityRepository
{
}
