<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
