<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaTarifaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaTarifaRepository extends \Doctrine\ORM\EntityRepository
{
}
