<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaCotizaServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaCotizaServiciosRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneWithCatalogo($id)
    {
        $manager = $this->getEntityManager();

        $conceptos = $manager->createQuery(
            'SELECT '.
            'concepto.id AS productoId, '.
            'concepto.cantidad AS conceptoCantidad, ' .
            'concepto.total AS conceptoImporte, '.
            'cotizacion.dolar AS conceptoDolar, '.
            'cps.id AS cpsId, cps.descripcion as cpsDescripcion, '.
            'cu.id AS cuId, cu.nombre AS cuDescripcion, '.
            '(CASE '.
            'WHEN concepto.tipo = 1 THEN \'Estadia\' '.
            'WHEN concepto.tipo = 2 THEN \'Electricidad\' '.
            'ELSE \'Sin descripción\' '.
            'END) AS conceptoDescripcion '.
            'FROM AppBundle:MarinaHumedaCotizaServicios concepto '.
            'LEFT JOIN concepto.marinahumedacotizacion cotizacion '.
            'LEFT JOIN AppBundle:Marina\Tarifa\Tipo tipo WITH tipo.tipo = concepto.tipo '.
            'LEFT JOIN tipo.claveProdServ cps '.
            'LEFT JOIN tipo.claveUnidad cu '.
            'WHERE IDENTITY(concepto.marinahumedacotizacion) = :id ')
            ->setParameter('id', $id)
            ->getArrayResult();

        return $conceptos;
    }
}
