<?php

namespace AppBundle\Repository;

/**
 * MarinaHumedaCotizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarinaHumedaCotizacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEstadia()
    {
        $qb = $this->createQueryBuilder('mhc');

        return $qb
            ->select('mhc', 'servicios')
            ->join('mhc.mhcservicios', 'servicios')
            ->where($qb->expr()->neq('servicios.tipo', '3'))
            ->getQuery()
            ->getResult();
    }

    public function findAllGasolina()
    {
        $qb = $this->createQueryBuilder('mhc');

        return $qb
            ->select('mhc', 'servicios')
            ->join('mhc.mhcservicios', 'servicios')
            ->where($qb->expr()->eq('servicios.tipo','3'))
            ->getQuery()
            ->getResult();
    }

}
