<?php

namespace AppBundle\Repository;

/**
 * ModificacionInventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificacionInventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
