<?php

namespace AppBundle\Repository;

/**
 * MonederoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonederoMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
