<?php

namespace AppBundle\Repository;

/**
 * MotorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorRepository extends \Doctrine\ORM\EntityRepository
{
}
