<?php

namespace AppBundle\Repository;

/**
 * OrdenDeTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDeTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
