<?php

namespace AppBundle\Repository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends \Doctrine\ORM\EntityRepository
{
    public function encuentraPaises()
    {
        $qb = $this->createQueryBuilder('p');

        return $qb->select('p.id','p.name as nombre')
            ->getQuery()
            ->getResult();
    }
}
