<?php

namespace AppBundle\Repository;

/**
 * PincodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PincodeRepository extends \Doctrine\ORM\EntityRepository
{
}
