<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * SlipMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlipMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $slip
     * @param $start
     * @param $end
     *
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function isSlipOpen($slip, $start, $end)
    {
        return $this->createQueryBuilder('sm')
            ->where('
                    sm.slip = :slip AND
                    ((:fechaLlegada BETWEEN sm.fechaLlegada AND sm.fechaSalida) OR
                     (:fechaSalida BETWEEN sm.fechaLlegada AND sm.fechaSalida))
                ')
            ->setParameters([
                'slip' => $slip,
                'fechaLlegada' => $start->format('Y-m-d'),
                'fechaSalida' => $end->format('Y-m-d'),
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getSlipInformation($slip, $cotizacion)
    {
        return $this->createQueryBuilder('sm')
            ->select('sm', 'slip', 'cotizacion', 'cliente', 'barco')
            ->where('sm.slip = :slip AND sm.marinahumedacotizacion = :cotizacion')
            ->leftJoin('sm.slip', 'slip')
            ->leftJoin('sm.marinahumedacotizacion', 'cotizacion')
            ->leftJoin('cotizacion.cliente', 'cliente')
            ->leftJoin('cotizacion.barco', 'barco')
            ->setParameters([
                'slip' => $slip,
                'cotizacion' => $cotizacion
            ])
            ->getQuery()
            ->getResult();
    }

    public function getCurrentOcupation($fecha)
    {
        return $this->createQueryBuilder('sm')
            ->select('sm', 'slip', 'cotizacion', 'cliente', 'barco')
            ->leftJoin('sm.slip', 'slip')
            ->leftJoin('sm.marinahumedacotizacion', 'cotizacion')
            ->leftJoin('cotizacion.cliente', 'cliente')
            ->leftJoin('cotizacion.barco', 'barco')
            ->where(':fecha BETWEEN sm.fechaLlegada AND sm.fechaSalida')
            ->setParameter('fecha', $fecha->format('Y-m-d'))
            ->getQuery()
            ->getResult();
    }

    public function getCurrentOcupationStats($fecha)
    {
        $slipRepository = $this->getEntityManager()->getRepository('AppBundle:Slip');

        $subquery = $slipRepository->createQueryBuilder('ss')
            ->select('COUNT(ss.id)')
            ->where('ss.pies = s.pies');

        return $this->createQueryBuilder('sm')
            ->select('s.pies',
                'COUNT(sm.id) AS ocupados',
                "({$subquery->getDQL()}) AS total")
            ->leftJoin('sm.slip', 's')
            ->where(':fecha BETWEEN sm.fechaLlegada AND sm.fechaSalida')
            ->groupBy('s.pies')
            ->orderBy('s.pies', 'ASC')
            ->setParameter('fecha', $fecha->format('Y-m-d'))
            ->getQuery()
            ->getScalarResult();
    }

    public function getTimelineEvents($start, $end)
    {
        return $this->createQueryBuilder('sm')
            ->select(
                'sm.id AS id',
                'IDENTITY(sm.slip) AS resourceId',
                'sm.fechaLlegada AS start',
                'sm.fechaSalida AS end',
                'CASE WHEN sm.nota IS NOT NULL THEN sm.nota ELSE b.nombre END AS title',
                'CASE WHEN sm.nota IS NOT NULL THEN \'#f3b41b\' ELSE \'#db245d\' END AS backgroundColor',
                'CASE WHEN sm.nota IS NOT NULL THEN \'#000\' ELSE \'#fff\' END AS textColor'
            )
            ->leftJoin('sm.marinahumedacotizacion', 'mhc')
            ->leftJoin('mhc.barco', 'b')
            ->where('((:start BETWEEN sm.fechaLlegada AND sm.fechaSalida) 
                OR (:end BETWEEN sm.fechaLlegada AND sm.fechaSalida))')
            ->orderBy('sm.slip')
            ->setParameters([
                'start' => $start->format('Y-m-d'),
                'end' => $end->format('Y-m-d')
            ])
            ->getQuery()
            ->getScalarResult();
    }
}
