<?php

namespace AppBundle\Repository;

/**
 * SlipMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlipMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
    public function ordenaFechasEstadia()
    {
        $qb = $this->createQueryBuilder('smov');

        return $qb
            ->select('smov')
            ->orderBy('smov.fechaLlegada','ASC')
            ->getQuery()
            ->getResult();
    }

    public function ordenaDescendente(){
        $qb = $this->createQueryBuilder('smov');
        return $qb
            ->select('smov')
            ->orderBy('smov.id','DESC')
            ->getQuery()
            ->getResult();
    }
}
