<?php

namespace AppBundle\Repository;

/**
 * ValorSistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorSistemaRepository extends \Doctrine\ORM\EntityRepository
{
}
