<?php

namespace AppBundle\Repository\Contabilidad\Facturacion;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * EmisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmisorRepository extends \Doctrine\ORM\EntityRepository
{
    public function pagination($page = 1, $length = 1, $order = 'DESC') : Paginator
    {
        $qb = $this->createQueryBuilder('emi');
        $qb
//            ->where('emi.estatus = 1')
            ->addOrderBy('emi.id', $order)
            ->setFirstResult($length * ((int)$page - 1))
            ->setMaxResults($length);

        $paginator = new Paginator($qb, false);

        return $paginator;
    }

    public function getEmisorRoles()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT em.id, em.alias '.
                'FROM AppBundle:Contabilidad\Facturacion\Emisor em'
            )
            ->getArrayResult();
    }
}
