<?php

namespace AppBundle\Repository\Tienda\Inventario;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
