<?php

namespace AppBundle\Repository\Astillero\Contratista;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
