<?php

namespace AppBundle\Repository\Astillero\Contratista;

use Doctrine\ORM\NonUniqueResultException;

/**
 * PagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoRepository extends \Doctrine\ORM\EntityRepository
{
}
