<?php

namespace AppBundle\Repository\Contabilidad\Catalogo;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends \Doctrine\ORM\EntityRepository
{
    public function createCodigo()
    {
        $manager = $this->getEntityManager();

        $max = $manager->createQuery(
            'SELECT servicio.codigo '.
            'FROM AppBundle:Contabilidad\\Catalogo\\Servicio servicio '.
            'ORDER BY servicio.id DESC ')
            ->setMaxResults(1)
            ->getSingleScalarResult();


        return 'S'.sprintf('%03d', preg_replace('/\D+/','', $max) + 1);
    }

    public function getSuggestions($query)
    {
        $manager = $this->getEntityManager();

        $suggestions = $manager->createQuery(
            'SELECT servicio.id, servicio.nombre AS text, ' .
            'cu.id AS cuId, cu.nombre AS cuDescripcion, '.
            'cps.id AS cpsId, cps.descripcion AS cpsDescripcion '.
            'FROM AppBundle:Contabilidad\\Catalogo\\Servicio servicio '.
            'LEFT JOIN servicio.claveUnidad cu '.
            'LEFT JOIN servicio.claveProdServ cps '.
            'WHERE LOWER(servicio.nombre) LIKE ?1')
            ->setParameter(1, strtolower("%{$query}%"))
            ->setMaxResults(10)
            ->getArrayResult();

        return $suggestions;
    }
}
