<?php

namespace AppBundle\Repository\Cliente;

/**
 * CuentaBancariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaBancariaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCuentasBancariasLikeSelect2($cliente, $query)
    {
        $manager = $this->getEntityManager();

        $cuentas = $manager->createQuery(
            'SELECT cuenta.id, cuenta.alias AS text '.
            'FROM AppBundle:Cliente\CuentaBancaria cuenta '.
            'WHERE cuenta.cliente = :cliente '.
            'OR cuenta.alias LIKE :query '.
            'OR cuenta.nombre LIKE :query '.
            'OR cuenta.numeroCuenta LIKE :query')
            ->setParameter('cliente', $cliente)
            ->setParameter('query', "%{$query}%")
            ->getArrayResult();

        return $cuentas;
    }
}
