<?php

namespace AppBundle\Repository\Cliente;

/**
 * CuentaBancariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaBancariaRepository extends \Doctrine\ORM\EntityRepository
{
}
