<?php

namespace AppBundle\Repository\Cliente;

/**
 * RazonSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RazonSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
