<?php

namespace AppBundle\Repository\Cliente;

/**
 * ReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReporteRepository extends \Doctrine\ORM\EntityRepository
{
}
