<?php

namespace AppBundle\Repository\Cliente;

/**
 * ReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReporteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return string
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getBRClient()
    {
        $qb = $this->createQueryBuilder('r')
            ->join('r.cliente', 'c');

        return $qb->select('c.nombre')
            ->orderBy('r.adeudo', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return float
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAdeudoTotal()
    {
        return $this->createQueryBuilder('r')
            ->select('SUM(r.adeudo)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return float
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAbonoTotal()
    {
        return $this->createQueryBuilder('r')
            ->select('SUM(r.abono)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
