<?php

namespace AppBundle\Repository\Gasto;

/**
 * ConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReporteGastos($idempresa,$idconcepto,$inicio,$fin)
    {
        $resultado = [];
        $granTotal = 0;
        $qry = 'SELECT concepto, servicio, gasto, emisor '.
            'FROM AppBundle:Gasto\Concepto concepto '.
            'LEFT JOIN concepto.servicio servicio '.
            'LEFT JOIN concepto.gasto gasto '.
            'LEFT JOIN gasto.empresa emisor '.
            'WHERE gasto.fecha BETWEEN :inicio AND :fin '.
            'ORDER BY gasto.fecha ASC';
        $conceptos = $this->getEntityManager()->createQuery($qry);
        $conceptos->setParameter('inicio',$inicio);
        $conceptos->setParameter('fin',date('Y-m-d H:i:s',strtotime('+23 hour +59 minutes +59 seconds',strtotime($fin))));

        foreach ($conceptos->getArrayResult() as $concepto){
            array_push($resultado,[
                'fecha' => $concepto['gasto']['fecha']->format('d/m/Y'),
                'empresa' => $concepto['gasto']['empresa']['nombre'],
                'concepto' => $concepto['servicio']['nombre'],
                'total' => $this->esMoneda($concepto['total']),
            ]);
            $granTotal+=$concepto['total'];
        }
        return $resultado;
    }

    function esMoneda($valor){
        return '$'.number_format($valor/100,2);
    }
}
