<?php

namespace AppBundle\Repository\Contabilidad;

/**
 * EgresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgresoRepository extends \Doctrine\ORM\EntityRepository
{
}
