<?php

namespace AppBundle\Repository\Contabilidad;

use AppBundle\Entity\Contabilidad\Facturacion;

/**
 * FacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturacionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCotizaciones($folio)
    {
        $folios = explode('-', $folio);
        $marinaCotizaciones = $this->getMarinaCotizacionesByFolio($folios[0], $folios[1] ?? null);
        $astilleroCotizaciones = $this->getAstilleroCotizacionesByFolio($folios[0], $folios[1] ?? null);
        $tiendaSolicitudes = $this->getTiendaSolicitudes($folios[0]);

        return $marinaCotizaciones + $astilleroCotizaciones + $tiendaSolicitudes;
    }

    public function getFacturaGlobal()
    {
        $em = $this->getEntityManager();
        $dql = '
        SELECT
        cotizacion,
        pagos,
        servicios,
        servicioBasico,
        servicioProducto,
        servicioRegular,
        cliente
        FROM AppBundle:AstilleroCotizacion AS cotizacion
        LEFT JOIN cotizacion.pagos AS pagos
        LEFT JOIN cotizacion.acservicios AS servicios
        LEFT JOIN cotizacion.cliente AS cliente
        LEFT JOIN cliente.razonesSociales AS razonSocial
        LEFT JOIN servicios.astilleroserviciobasico AS servicioBasico
        LEFT JOIN servicios.producto AS servicioProducto
        LEFT JOIN servicios.servicio AS servicioRegular
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND cliente.id IS NOT NULL
        AND pagos.factura IS NULL
        AND razonSocial.id IS NULL
        ';

        $atQuery = $em->createQuery($dql)->getResult();

        $dql = '
        SELECT 
        cotizacion,
        pagos,
        servicio,
        movimiento,
        cliente
        FROM AppBundle:MarinaHumedaCotizacion AS cotizacion
        LEFT JOIN cotizacion.pagos AS pagos
        LEFT JOIN cotizacion.mhcservicios AS servicio
        LEFT JOIN cotizacion.slipmovimiento AS movimiento
        LEFT JOIN cotizacion.cliente AS cliente
        LEFT JOIN cliente.razonesSociales AS razonSocial
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND cliente.id IS NOT NULL
        AND pagos.factura IS NULL
        AND razonSocial.id IS NULL
        ';

        $mhQuery = $em->createQuery($dql)->getResult();


        return array_merge($mhQuery, $atQuery);
    }

    public function getPagosFacturaGlobal()
    {
        $em = $this->getEntityManager();
        $dql = '
        SELECT
        pagos
        FROM AppBundle:Pago AS pagos
        LEFT JOIN pagos.acotizacion AS cotizacion
        LEFT JOIN cotizacion.cliente AS cliente
        LEFT JOIN cliente.razonesSociales AS razonSocial
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND pagos.factura IS NULL
        AND razonSocial.id IS NULL
        ';

        $atQuery = $em->createQuery($dql)->getResult();

        $dql = '
        SELECT
        pagos
        FROM AppBundle:Pago AS pagos
        LEFT JOIN pagos.mhcotizacion AS cotizacion
        LEFT JOIN cotizacion.cliente AS cliente
        LEFT JOIN cliente.razonesSociales AS razonSocial
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND pagos.factura IS NULL
        AND razonSocial.id IS NULL
        ';

        $mhQuery = $em->createQuery($dql)->getResult();


        return array_merge($mhQuery, $atQuery);
    }

    public function getPagosByFolioCotizacion($folio, $folioRecotizado = null)
    {
        $em = $this->getEntityManager();
        $dql = '
        SELECT 
        pagos, mhc, atc, tienda, movimiento
        FROM AppBundle:Pago AS pagos
        LEFT JOIN pagos.mhcotizacion AS mhc
        LEFT JOIN pagos.acotizacion AS atc
        LEFT JOIN pagos.tiendasolicitud AS tienda
        LEFT JOIN mhc.slipmovimiento AS movimiento
        WHERE pagos.factura IS NULL
        AND mhc.folio = :folio OR atc.folio = :folio OR tienda.folio = :folio
        ';

        if ($folioRecotizado) {
            $dql .= 'AND mhc.foliorecotiza = :foliorecotizado OR atc.foliorecotiza = :foliorecotizado';
            $query = $em->createQuery($dql)
                ->setParameter(':folio', $folio)
                ->setParameter(':foliorecotizado', $folioRecotizado);
        } else {
            $query = $em->createQuery($dql)
                ->setParameter(':folio', $folio);
        }

        return $query->getResult();
    }

    private function getMarinaCotizacionesByFolio($folio, $folioRecotizado = null)
    {
        $em = $this->getEntityManager();
        $dql = '
        SELECT 
        cotizacion,
        pagos,
        servicio,
        movimiento
        FROM AppBundle:MarinaHumedaCotizacion AS cotizacion
        LEFT JOIN cotizacion.pagos AS pagos
        LEFT JOIN cotizacion.mhcservicios AS servicio
        LEFT JOIN cotizacion.slipmovimiento AS movimiento
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND pagos.factura IS NULL
        AND cotizacion.folio LIKE :folio
        ';

        if ($folioRecotizado) {
            $dql .= 'AND cotizacion.foliorecotiza LIKE :foliorecotiza';
            $query = $em->createQuery($dql)
                ->setParameter('folio', "%{$folio}%")
                ->setParameter('foliorecotiza', "%{$folioRecotizado}%");
        } else {
            $query = $em->createQuery($dql)
                ->setParameter('folio', "%{$folio}%");
        }

        return $query->getResult();
    }

    private function getAstilleroCotizacionesByFolio($folio, $folioRecotizado = null)
    {
        $em = $this->getEntityManager();
        $dql = '
        SELECT
        cotizacion,
        pagos,
        servicios,
        servicioBasico,
        servicioProducto,
        servicioRegular
        FROM AppBundle:AstilleroCotizacion AS cotizacion
        LEFT JOIN cotizacion.pagos AS pagos
        LEFT JOIN cotizacion.acservicios AS servicios
        LEFT JOIN servicios.astilleroserviciobasico AS servicioBasico
        LEFT JOIN servicios.producto AS servicioProducto
        LEFT JOIN servicios.servicio AS servicioRegular
        WHERE cotizacion.validanovo = 2
        AND pagos.id IS NOT NULL
        AND pagos.factura IS NULL
        AND cotizacion.folio LIKE :folio
        ';

        if ($folioRecotizado) {
            $dql .= 'AND cotizacion.foliorecotiza LIKE :foliorecotiza';
            $query = $em->createQuery($dql)
                ->setParameter('folio', "%{$folio}%")
                ->setParameter('foliorecotiza', "%{$folioRecotizado}%");
        } else {
            $query = $em->createQuery($dql)
                ->setParameter('folio', "%{$folio}%");
        }

        return $query->getResult();
    }

    private function getTiendaSolicitudes($folio)
    {
        $repository = $this->getEntityManager()->getRepository('AppBundle:Tienda\Solicitud');
        $query = $repository->createQueryBuilder('solicitud');

        $query
            ->select('solicitud, peticion, producto, pagos')
            ->leftJoin('solicitud.pagos', 'pagos')
            ->leftJoin('solicitud.producto', 'peticion')
            ->leftJoin('peticion.producto', 'producto')
            ->where('solicitud.folio LIKE :folio AND pagos.id IS NOT NULL and pagos.factura IS NULL')
            ->setParameter('folio', "%{$folio}%");

        return $query->getQuery()->getResult();
    }

    /**
     * @param $id
     *
     * @return Facturacion
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFactura($id)
    {
        $manager = $this->getEntityManager();
        $factura = $manager
            ->createQuery(
                'SELECT factura, emisor, conceptos '.
                'FROM AppBundle:Contabilidad\Facturacion factura '.
                'LEFT JOIN factura.emisor emisor '.
                'LEFT JOIN factura.conceptos conceptos '.
                'WHERE factura.id = ?1'
            )
            ->setParameter(1, $id)
            ->setMaxResults(1)
            ->getOneOrNullResult();

        $manager->createQuery(
            'SELECT PARTIAL conceptos.{id}, claveUnidad '.
            'FROM AppBundle:Contabilidad\Facturacion\Concepto conceptos '.
            'LEFT JOIN conceptos.claveUnidad claveUnidad'
        );

        $manager->createQuery(
            'SELECT PARTIAL conceptos.{id}, CPS '.
            'FROM AppBundle:Contabilidad\Facturacion\Concepto conceptos '.
            'LEFT JOIN conceptos.claveProdServ CPS'
        );

        return $factura;
    }

    public function getFolioByEmpresa($empresa) {
        $manager = $this->getEntityManager();

        $folio = $manager
            ->createQuery(
              'SELECT COUNT(factura.id) '.
              'FROM AppBundle:Contabilidad\Facturacion factura '.
              'LEFT JOIN AppBundle:Contabilidad\Facturacion\Pago pagos WITH pagos.factura = factura '.
              'WHERE IDENTITY(factura.emisor) = :empresa'
            )
            ->setParameter('empresa', $empresa)
            ->setMaxResults(1)
            ->getSingleScalarResult();

        return $folio + 1;
    }
}
