<?php

namespace AppBundle\Repository\Contabilidad\Facturacion\Concepto;

/**
 * ClaveProdServRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaveProdServRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLike($query)
    {
        $qb = $this->createQueryBuilder('cps');

        return $qb
            ->where($qb->expr()->like('cps.descripcion', ':query'))
            ->orWhere($qb->expr()->like('cps.claveProdServ', ':query'))
            ->setParameter('query', "%{$query}%")
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();
    }
}
