<?php

namespace AppBundle\Repository\Contabilidad\Facturacion\Concepto;

/**
 * ClaveProdServRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaveProdServRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLikeSelect2($query)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT cps.id, cps.descripcion AS text '.
                'FROM AppBundle:Contabilidad\Facturacion\Concepto\ClaveProdServ cps '.
                'WHERE cps.descripcion LIKE ?1 OR cps.claveProdServ LIKE ?1'
            )
            ->setParameter(1, "%{$query}%")
            ->setMaxResults(10)
            ->getArrayResult();
    }
}
