<?php

namespace AppBundle\Repository\Contabilidad\Egreso\Entrada;

/**
 * ConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getConceptosByEmpresaAndNombre($empresaId, $nombre)
    {
        return $this->createQueryBuilder('c')
            ->where('IDENTITY(c.empresa) = ?1 AND c.descripcion LIKE ?2')
            ->setParameter(1, $empresaId)
            ->setParameter(2, "%{$nombre}%")
            ->getQuery()
            ->getArrayResult();
    }
}
