<?php

namespace AppBundle\Repository\Contabilidad\Egreso\Entrada;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends \Doctrine\ORM\EntityRepository
{

    public function getProveedorLike($stringValue)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.nombre '.
                'FROM AppBundle:Contabilidad\Egreso\Entrada\Proveedor p '.
                'WHERE p.nombre LIKE ?1'
            )
            ->setParameter(1, "%{$stringValue}%")
            ->setMaxResults(5)
            ->getArrayResult();
    }
}
