<?php

namespace AppBundle\Repository\Astillero\Contratista\Actividad;

/**
 * PausaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PausaRepository extends \Doctrine\ORM\EntityRepository
{
}
